name: Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    release-npm:
        name: Release NPM (${{ github.ref }})
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check if Tag on Main
              run: |
                  git checkout main
                  branch=$(git branch main --contains ${{ github.ref }})
                  git checkout ${{ github.ref }}
                  if [ -z $branch ]; then
                      echo "Tag ${{ github.ref }} is not contained in the main branch."
                      exit 1
                  fi

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build & Test
              run: pnpm build && pnpm test

            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}

    release-note:
        name: Release Note (${{ github.ref }})
        runs-on: ubuntu-latest
        needs:
            - release-npm
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check if Tag on Main
              run: |
                  git checkout main
                  branch=$(git branch main --contains ${{ github.ref }})
                  git checkout ${{ github.ref }}
                  if [ -z $branch ]; then
                      echo "Tag ${{ github.ref }} is not contained in the main branch."
                      exit 1
                  fi

            - name: Publish Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GH_TOKEN }}"
                  prerelease: false
                  files: |
                      README.md
                      LICENSE
