name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                version:
                    - "latest"
                    - "2024.12.1"
                    - "2024.10.1"
                    - "2024.8.3"
                    - "2024.6.1"

        name: "${{ matrix.os }} - ${{ matrix.version }}"
        runs-on: ${{ matrix.os }}
        timeout-minutes: 15
        env:
            VERBOSE: 1
            TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
            CLOUDFLARED_VERSION: ${{ matrix.version }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Build
              run: pnpm build

            - name: Test (w/ service)
              run: sudo -E $PNPM_HOME/pnpm test
              if: matrix.os != 'windows-latest'

            - name: Test (w/o service)
              run: pnpm test
              if: matrix.os == 'windows-latest'
