name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                version:
                    - "latest"
                    - "2023.6.1"
                    - "2023.4.2"
                    - "2023.2.2"
                    - "2022.12.1"

        name: "${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        env:
            VERBOSE: 1
            TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
            CLOUDFLARED_VERSION: ${{ matrix.version }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.4.0
              with:
                  run_install: true

            - name: Build
              run: pnpm build

            - name: Test (w/ service)
              run: sudo -E $PNPM_HOME/pnpm test
              if: matrix.os != 'windows-latest'

            - name: Test (w/o service)
              run: pnpm test
              if: matrix.os == 'windows-latest'
